spring:
  data:
    mongodb:
      username: cutemeet
      password: cutemeet
      host: localhost
      port: 27017
      database: cutemeet_chat
      authentication-database: admin
server:
  port: 8088